In [2]:
import numpy as np
from src.quantumcircuit.qc_elementary_matrices import rz01, rx01
from src.decomposition.transpilation import SU3_matrices

In [8]:
sigma2 = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
sigma3 = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
sigma4 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
sigma5 = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
sigma6 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

In [9]:
su3_sigma2 = SU3_matrices(su3=sigma2, qutrit_index=0, n_qutrits=1)
print("Reconstructing ...")
print(f"{su3_sigma2.reconstruct().round()}\n{sigma2}")

Reconstructing ...
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.-0.j]
 [0.+0.j 1.-0.j 0.+0.j]]
[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [22]:
su3_sigma2

U_diagonal:
[[1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 6.123234e-17+1.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17+1.j]]
R_theta1:
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]]
R_theta2:
[[1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 6.123234e-17+0.j 0.000000e+00-1.j]
 [0.000000e+00+0.j 0.000000e+00-1.j 6.123234e-17+0.j]]
R_theta3:
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]]

In [10]:
su3_sigma3 = SU3_matrices(su3=sigma3, qutrit_index=0, n_qutrits=1)
print("Reconstructing ...")
print(f"{su3_sigma3.reconstruct().round()}\n{sigma3}")

Reconstructing ...
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.-0.j]
 [0.+0.j 1.-0.j 0.+0.j]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]


In [11]:
x01 = np.array([[0, 1.0, 0], [1.0, 0, 0], [0, 0, 1.0]])
su_x = SU3_matrices(x01, 0, 1)
su_x.reconstruct().round()

array([[ 0.+0.j,  1.-0.j,  0.+0.j],
       [-1.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [12]:
su_x.unitary_diagonal()

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [13]:
su_x.rotation_theta3_01().round()

array([[ 0.+0.j,  1.-0.j,  0.+0.j],
       [-1.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [14]:
su_x.rotation_theta2_12()

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [15]:
su_x.rotation_theta1_01().round()

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [16]:
phi3 = su_x.parameters.__getattribute__("phi3")

phi3

-1.5707963267948966

In [21]:
theta3 = su_x.parameters.__getattribute__("theta3")

theta3

3.141592653589793

In [18]:
rx01(theta3).round()

array([[0.+0.j, 0.-1.j, 0.+0.j],
       [0.-1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [19]:
rz01(phi3).round()

array([[0.-1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

In [11]:
rz01(-phi3).round()

array([[0.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.-1.j]])

array([[ 6.123234e-17+0.000000e+00j, -1.000000e+00-6.123234e-17j,
         0.000000e+00+0.000000e+00j],
       [ 1.000000e+00-6.123234e-17j,  6.123234e-17+0.000000e+00j,
         0.000000e+00+0.000000e+00j],
       [ 0.000000e+00+0.000000e+00j,  0.000000e+00+0.000000e+00j,
         1.000000e+00+0.000000e+00j]])